name: GitHub Release

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.16"
      - name: Build (linux amd64)
        run: go build -o sshesame-linux-amd64
        env:
          GOOS: linux
          GOARCH: amd64
      - name: Build (linux arm)
        run: go build -o sshesame-linux-arm
        env:
          GOOS: linux
          GOARCH: arm
      - name: Build (linux arm64)
        run: go build -o sshesame-linux-arm64
        env:
          GOOS: linux
          GOARCH: arm64
      - name: Build (darwin amd64)
        run: go build -o sshesame-macos-amd64
        env:
          GOOS: darwin
          GOARCH: amd64
      - name: Build (darwin arm64)
        run: go build -o sshesame-macos-arm64
        env:
          GOOS: darwin
          GOARCH: arm64
      - name: Build (windows amd64)
        run: go build -o sshesame-windows-amd64.exe
        env:
          GOOS: windows
          GOARCH: amd64
      - name: Build (windows arm)
        run: go build -o sshesame-windows-arm.exe
        env:
          GOOS: windows
          GOARCH: arm
      - name: Build (windows arm64)
        run: go build -o sshesame-windows-arm64.exe
        env:
          GOOS: windows
          GOARCH: arm64
      - name: Tag
        uses: actions/tag-version@v2
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            sshesame-linux-amd64
            sshesame-linux-arm
            sshesame-linux-arm64
            sshesame-macos-amd64
            sshesame-macos-arm64
            sshesame-windows-amd64.exe
            sshesame-windows-arm.exe
            sshesame-windows-arm64.exe
