name: Release binaries
on:
  push:
    tags:
      - v*
jobs:
  release-binaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.16"
      - run: go build -o sshesame-linux-amd64
        env:
          GOOS: linux
          GOARCH: amd64
      - run: go build -o sshesame-linux-armv6
        env:
          GOOS: linux
          GOARCH: arm
          GOARM: 6
      - run: go build -o sshesame-linux-armv7
        env:
          GOOS: linux
          GOARCH: arm
          GOARM: 7
      - run: go build -o sshesame-linux-arm64
        env:
          GOOS: linux
          GOARCH: arm64
      - run: go build -o sshesame-macos-amd64
        env:
          GOOS: darwin
          GOARCH: amd64
      - run: go build -o sshesame-macos-arm64
        env:
          GOOS: darwin
          GOARCH: arm64
      - run: go build -o sshesame-windows-amd64.exe
        env:
          GOOS: windows
          GOARCH: amd64
      - run: go build -o sshesame-windows-armv7.exe
        env:
          GOOS: windows
          GOARCH: arm
          GOARM: 7
      - run: go build -o sshesame-windows-arm64.exe
        env:
          GOOS: windows
          GOARCH: arm64
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            sshesame-linux-amd64
            sshesame-linux-armv6
            sshesame-linux-armv7
            sshesame-linux-arm64
            sshesame-macos-amd64
            sshesame-macos-arm64
            sshesame-windows-amd64.exe
            sshesame-windows-armv7.exe
            sshesame-windows-arm64.exe
            sshesame.yaml
